apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
  data:
    prometheus.yaml: |
      global:
        scrape_interval: 30
      scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - localhost:9090
