apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      envFrom:
      - prefix: MONGO
        configMapRef:
          name: mongodb-config
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: mongodb-pvc

