apiVersion: v1
kind: Pod
metadata:
    name: nginx
    namespace: webserver
spec:
    containers:
    - image: nginx
      name: nginx
      ports:
      -  containerPort: 8080
         protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 8081
        initialDelaySeconds: 20
