apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - "while true; do sleep 3600; done"
        tty: true
        stdin: true

