<<<<<<< HEAD
epiVersion: apps/v1
=======
apiVersion: apps/v1
>>>>>>> origin/main
kind: StatefulSet
metadata:
  name: busybox
spec:
<<<<<<< HEAD
  serviceName: "busybox"
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
=======
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
>>>>>>> origin/main
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - "while true; do sleep 3600; done"
        tty: true
        stdin: true

